### PR TITLE
[FIX] Clear occupied slots after character leaves space

### LINKED ISSUE #714: Clear kicked/banned players from device slots automatically
Currently, the "clear occupancy of the slot" is a way for admins to clean up after any sync issues, such as someone being kicked from the space. If they just kick and forget to clear the slot, then no one one else that is not admin can clear it and use it again.

I just tested it, and if the one kicked joins again, then even the admin can no longer clear the slot and they have to undeploy and deploy again. It is a bit of an inconvenient that this is a manual step that can easily be forgotten.

This issue is about investigating if admin action could have an automated clean-up step that clears the target from all slots in all devices of the space (by cycling through them).

Note: When Pandora's Space Service kicks some ghost out of a room device, it should also clear the slot.

### PR DESCRIPTION
**Pull request by XenonRope**
Fixes #714 

Slots occupied by characters that left the space (e.g. kicked/banned) will be cleared automatically. The button "Clear occupancy of the slot" should never be visible to a player but I left this button just in case.

There is still one minor issue: If a character is restrained to Bondage Cross with "Module: Chains" set to "Tied front-facing" and the character is kicked, the "Module: Chains" is still set to "Tied front-facing". To use Bondage Cross again, the "Module: Chains" must be set to "Not attached" manually. I didn't change that because it seems to work as expected. I can create a new Bondage Cross and set "Module: Chains" to "Tied front-facing" even if no character is restrained (the slot is empty).

### CODE REVIEW

File: pandora-server-shard/src/spaces/space.ts [hunk 1]
```diff
@@ -554,3 +556,23 @@ export abstract class Space extends ServerRoom<IShardClient> {
 function IsTargeted(message: IClientMessage): message is { type: 'chat' | 'ooc'; parts: IChatSegment[]; to: CharacterId; } {
 	return (message.type === 'chat' || message.type === 'ooc') && message.to !== undefined;
 }
+
+function ClearOccupiedSlotsByCharacter(globalState: AssetFrameworkGlobalState, characterId: CharacterId): AssetFrameworkGlobalState {
```
Comment (Sekkmer) [inline pandora-server-shard/src/spaces/space.ts:560]: I feel this code should not be shard specific, instead moved to `withCharacter` function

Comment (XenonRope) [reply pandora-server-shard/src/spaces/space.ts]: I agree. I moved this logic to `withCharacter` function and added two unit tests.

**Review by Sekkmer — APPROVED** [review]
Looks good for me.

File: pandora-common/src/assets/state/globalState.ts [hunk 2]
```diff
@@ -172,7 +174,7 @@ export class AssetFrameworkGlobalState {
 		return new AssetFrameworkGlobalState(
 			this.assetManager,
 			newCharacters,
-			this.room,
+			newRoom,
```
Comment (Jomshir98) [inline pandora-common/src/assets/state/globalState.ts:177]: When a room state changes, all existing characters _must_ be updated using `character.updateRoomStateLink(newState, false)`, otherwise they will still have links to the old room state.
In this specific case, this would break things for multi-character room devices - when one of the characters leave, the device itself is updated, but the other character in it would still have internally link to the old state.
See `withRoomState` for the loop that needs to be added.

**Review by Jomshir98 — CHANGES_REQUESTED** [review]
Hi! Looks good, except the one usecase that breaks multi-character devices if one of the characters leave. See my comment below for more details.

File: pandora-common/src/assets/state/globalState.ts (hunk 2 above)
Comment (XenonRope) [reply pandora-common/src/assets/state/globalState.ts:175]: You're right, I didn't notice this. I created the method `_updateRoomStateLinkOnCharacters` and added its invocation here. Additionally, I added a unit test for exactly this case. To make tests more readable I added `stateUtils.ts` as well.

**Review by Jomshir98 — APPROVED** [review]
Looks good to me now! Thank you!
